# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
cache: cocoapods
podfile: Example-Swift/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example-Swift
script:
- set -o pipefail && xcodebuild -workspace Example-Swift/TTGSnackbarExample.xcworkspace -scheme TTGSnackbarExample ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint